function(add_broportal_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE broportal::broportal)
    target_include_directories(${name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../src)
    broportal_warnings(${name})
    add_test(NAME ${name} COMMAND ${name})
    set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
endfunction()

add_broportal_test(test_types)
add_broportal_test(test_dbus_helpers)
add_broportal_test(test_request_session)
add_broportal_test(test_filechooser)
add_broportal_test(test_screenshot)
add_broportal_test(test_screencast)
add_broportal_test(test_remotedesktop)
add_broportal_test(test_settings)
add_broportal_test(test_inhibit)
add_broportal_test(test_openuri)
add_broportal_test(test_globalshortcuts)
add_broportal_test(test_full_backend)
